enableVolumeScheduling: true
enableVolumeResizing: true
enableVolumeSnapshot: true

node:
  kubeletPath: /opt/rke/var/lib/kubelet

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

extraVolumeTags:
  Name: k8s-aws-ebs-csi-volume
